liip_imagine:
    filter_sets:
        miniature:
            quality: 75
            filters:
                thumbnail:
                    size:   [30, 30]
                    mode:   outbound
        miniature100x100:
            quality: 75
            filters:
                thumbnail:
                    size:   [100, 100]
                    mode:   outbound
        profile_menu:
            quality: 80
            filters:
                thumbnail:
                    size:   [36, 36]
                    mode:   outbound
        img_operations:
            quality: 100
            filters:
                thumbnail:
                    size:   [160, 50]
            
    
    
#liip_imagine:
#    # valid drivers options include "gd" or "gmagick" or "imagick"
#    driver: "gd"
#
#    # define your filter sets under this option
#    filter_sets:
#
#        # an example thumbnail transformation definition
#        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
#        squared_thumbnail:
#
#            # set your image quality defaults
#            jpeg_quality:          85
#            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
#            filters:
#
#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~
#
#                # strip the image of all metadata
#                strip: ~
#
#                # scale and square the image to the given dimensions
#                thumbnail:
#                    size:          [253, 253]
#                    mode:          outbound
#                    allow_upscale: true
#
#                # create border by placing image on larger black background
#                background:
#                    size:     [256, 256]
#                    position: center
#                    color:    '#fff'
