home:
    path: /
    controller: App\AdminBundle\Controller\SecurityController::login
adminhome:
    path: /admin/
    controller: App\AdminBundle\Controller\SecurityController::login

api_login_check:
    path: /api/login_check
